name: CD

on:
  push:
    tags:
      - 'v*.*.*' # Enforce Semantic Versioning

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CD Environment
      uses: yetanalytics/actions/setup-env@v0.0.4

    - name: Extract version
      id: version
      run: echo version=${GITHUB_REF#refs\/tags\/v} >> $GITHUB_OUTPUT

    - name: Build and deploy to Clojars
      uses: yetanalytics/action-deploy-clojars@v1
      with:
          artifact-id: 'flint'
          resource-dirs: '[]'
          version: ${{ steps.version.outputs.version }}
          clojars-username: ${{ secrets.CLOJARS_USERNAME }}
          clojars-deploy-token: ${{ secrets.CLOJARS_PASSWORD }}
